/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EVDict4_1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class PracticeForm extends javax.swing.JFrame {
    public Timer time_to_guess;
    public int time_iterator = 1;
    public Random rd = new Random();
    public int level = 1;
    public String random_word_answer = "";
    public String hide_word_answer = "";
    public ArrayList<String> word_list_data;
    VoiceImplement speaker = new VoiceImplement();
    DictionaryData da = new DictionaryData();
    /**
     * Creates new form PracticeForm
     */
    public PracticeForm() {
        initComponents();
        resetDefault();
    }
    public void resetDefault() {
        time_iterator = 1;
        userGuessTextField.setText("");
        resultLabel.setText("");
        timeDisplayLabel.setVisible(false);
        clockIconLabel.setVisible(false);
        guess_WordAnswerLabel.setVisible(false);
        submitButton.setVisible(false);
        interfaceLabel.setVisible(false);
        nextWordButton.setVisible(false);
        userGuessTextField.setVisible(false);
        resultLabel.setVisible(false);
        userInterfaceLabel.setVisible(false);
    }
    public void showInterface() {
        timeDisplayLabel.setVisible(true);
        clockIconLabel.setVisible(true);
        guess_WordAnswerLabel.setVisible(true);
        submitButton.setVisible(true);
        interfaceLabel.setVisible(true);
        nextWordButton.setVisible(true);
        levelComboBox.setVisible(false);
        userGuessTextField.setVisible(true);
        resultLabel.setVisible(true);
        userInterfaceLabel.setVisible(true);
    }

    public void getRandomWord() {
        int random_number;
        if (level == 1) {
            word_list_data = da.getMarkedWord();
            random_number = rd.nextInt(word_list_data.size());
            random_word_answer = word_list_data.get(random_number);
        } else if (level == 2) {
            word_list_data = da.getRecentWord();
            random_number = rd.nextInt(word_list_data.size());
            random_word_answer = word_list_data.get(random_number);
        }
        hide_word_answer = random_word_answer;
        char[] tmp_hide_word_answer = hide_word_answer.toCharArray();
        int hide_character1 = hide_word_answer.length() / 2;
        int hide_character2 = 0;
        int hide_character3 = 0;
        if((hide_character1 - 1) >= 0) {
            hide_character2 = hide_character1 - 1;
        }
        if((hide_character1 + 1) <= hide_word_answer.length()) {
            hide_character3 = hide_character1 + 1;
        }
        tmp_hide_word_answer[hide_character1] = '_';
        tmp_hide_word_answer[hide_character2] = '_';
        tmp_hide_word_answer[hide_character3] = '_';
        hide_word_answer = String.valueOf(tmp_hide_word_answer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        timeDisplayLabel = new javax.swing.JLabel();
        clockIconLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        levelComboBox = new javax.swing.JComboBox<>();
        interfaceLabel = new javax.swing.JLabel();
        guess_WordAnswerLabel = new javax.swing.JLabel();
        nextWordButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        userInterfaceLabel = new javax.swing.JLabel();
        userGuessTextField = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        timeDisplayLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        clockIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EVDict4_1/Icon/clock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(timeDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clockIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clockIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        submitButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        levelComboBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level1", "Level2" }));
        levelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelComboBoxActionPerformed(evt);
            }
        });

        interfaceLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        interfaceLabel.setText("Guess word: ");

        guess_WordAnswerLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        guess_WordAnswerLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nextWordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EVDict4_1/Icon/nextWord.png"))); // NOI18N
        nextWordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextWordButtonActionPerformed(evt);
            }
        });

        userInterfaceLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userInterfaceLabel.setText("Guess: ");

        userGuessTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userGuessTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userGuessTextFieldMouseClicked(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(userInterfaceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userGuessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInterfaceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userGuessTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(interfaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guess_WordAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(89, 89, 89)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextWordButton))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guess_WordAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interfaceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextWordButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        getRandomWord();
        timeDisplayLabel.setText("");
        startButton.setVisible(false);
        showInterface();
        guess_WordAnswerLabel.setText(hide_word_answer);
            time_to_guess = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if(time_iterator <= 60) {
                        timeDisplayLabel.setText(String.valueOf(time_iterator) + "S");
                        time_iterator++;
                    }
                    else {
                        resetDefault();
                        guess_WordAnswerLabel.setVisible(true);
                        nextWordButton.setVisible(true);
                        guess_WordAnswerLabel.setText(String.format("%40s","TIME OUT !!"));
                    }
                }
            });
        time_to_guess.start();
    }//GEN-LAST:event_startButtonActionPerformed

    private void levelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelComboBoxActionPerformed
        // TODO add your handling code here:
        String level_selected = levelComboBox.getSelectedItem().toString();
        if(level_selected.equals("Level1")) {
            level = 1;
        }
        if(level_selected.equals("Level2")) {
            level = 2;
        }
    }//GEN-LAST:event_levelComboBoxActionPerformed

    private void nextWordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextWordButtonActionPerformed
        // TODO add your handling code here:
        resetDefault();
        time_to_guess.stop();
        startButton.setVisible(true);
        levelComboBox.setVisible(true);
    }//GEN-LAST:event_nextWordButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        if(userGuessTextField.getText().equals(random_word_answer)) {
            timeDisplayLabel.setVisible(false);
            clockIconLabel.setVisible(false);
            resultLabel.setText("Congratulation!!");
            speaker.HandleVoice("Correct answer");
        }
        else {
            resultLabel.setText("Wrong answer!!");
            speaker.HandleVoice("You need to practice more");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void userGuessTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userGuessTextFieldMouseClicked
        // TODO add your handling code here:
        userGuessTextField.setText("");
        resultLabel.setText("");
    }//GEN-LAST:event_userGuessTextFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockIconLabel;
    private javax.swing.JLabel guess_WordAnswerLabel;
    private javax.swing.JLabel interfaceLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> levelComboBox;
    private javax.swing.JButton nextWordButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel timeDisplayLabel;
    private javax.swing.JTextField userGuessTextField;
    private javax.swing.JLabel userInterfaceLabel;
    // End of variables declaration//GEN-END:variables
}
